import { motion } from 'framer-motion';

const STEPS = [
  {
    n: '01',
    title: 'Identify',
    body: 'Resolves the company name to the right ticker & exchange — US or Indian (NSE/BSE), preferring the home listing.',
  },
  {
    n: '02',
    title: 'Gather',
    body: 'Pulls fundamentals, a live market snapshot and recent news in parallel — every figure traced to a source.',
  },
  {
    n: '03',
    title: 'Analyze',
    body: 'Scores six dimensions — financial health, growth, valuation, profitability, sentiment and risk.',
  },
  {
    n: '04',
    title: 'Decide',
    body: 'Weighs bull vs bear through your chosen lens and returns an INVEST / WATCH / PASS verdict with conviction.',
  },
];

const FAQS = [
  {
    q: 'Where does the data come from?',
    a: 'Fundamentals, market quotes and news are sourced live from Yahoo Finance (US + Indian markets). Reasoning is generated by Google Gemini.',
  },
  {
    q: 'Is this financial advice?',
    a: 'No. It is an AI research tool for educational purposes. Always do your own due diligence before investing.',
  },
  {
    q: 'What do the verdicts mean?',
    a: 'INVEST = attractive now · WATCH = promising but not yet · PASS = avoid for now. Each comes with a 0–100 conviction score.',
  },
  {
    q: 'Can I compare two companies?',
    a: 'Yes — switch to Compare mode to run two side-by-side and get a head-to-head summary for your chosen investor lens.',
  },
];

export function HowItWorks() {
  return (
    <>
      <section id="how" className="mx-auto max-w-6xl px-4 py-16">
        <SectionHeading kicker="How it works" title="From a name to a verdict in four steps" />
        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {STEPS.map((s, i) => (
            <motion.div
              key={s.n}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-60px' }}
              transition={{ delay: i * 0.06 }}
              className="glass rounded-2xl p-5"
            >
              <div className="text-sm font-semibold text-indigo-400">{s.n}</div>
              <h3 className="mt-2 text-lg font-semibold text-slate-100">{s.title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-slate-400">{s.body}</p>
            </motion.div>
          ))}
        </div>
      </section>

      <section id="faq" className="mx-auto max-w-3xl px-4 py-16">
        <SectionHeading kicker="FAQ" title="Good to know" />
        <div className="mt-8 space-y-3">
          {FAQS.map((f) => (
            <details key={f.q} className="glass group rounded-xl p-4">
              <summary className="flex cursor-pointer list-none items-center justify-between text-slate-100">
                <span className="font-medium">{f.q}</span>
                <span className="text-slate-500 transition group-open:rotate-45">+</span>
              </summary>
              <p className="mt-3 text-sm leading-relaxed text-slate-400">{f.a}</p>
            </details>
          ))}
        </div>
      </section>
    </>
  );
}

function SectionHeading({ kicker, title }: { kicker: string; title: string }) {
  return (
    <div className="text-center">
      <div className="text-xs font-semibold uppercase tracking-wider text-indigo-400">{kicker}</div>
      <h2 className="mt-2 text-2xl font-bold text-slate-100 sm:text-3xl">{title}</h2>
    </div>
  );
}
